title: Sam Sutherland
email: sam.sutherland@hotmail.co.uk
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: snoodmcguinness.github.io
url: https://snoodmcguinness.github.io
baseurl: ""

theme: minima

author:
  name: Sam Sutherland
  email: sam.sutherland@hotmail.co.uk

github_username: SnoodMcGuinness
linkedin_username: <your-handle>

minima:
  social_links:
    google_scholar: https://scholar.google.com/citations?user=<your_id>
  
header_pages:
  - ml.md
  - about.md
  - cv.md
  - personal.md

show_excerpts: true

plugins:
  - jekyll-feed